name: Docker Image CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: https://index.docker.io/v1/
        username: dockerjulienm
        password: ${{ secrets.DOCKER_PAT }}
    - name: Build and push Docker image
      run: |
        docker build -t dockerjulienm/ttcompanion:latest . --file Dockerfile
        docker push dockerjulienm/ttcompanion:latest
    - name: Deploy to Render
      if: github.ref == 'refs/heads/main'
      run: |
        curl "${{ secrets.RENDER_DEPLOY_HOOK_LINK }}"